# agents/strategist.py
from core.ainx_message import AINXMessage

class StrategistAgent:
    def __init__(self):
        self.name = "StrategistAgent"

    def handle(self, message: AINXMessage) -> AINXMessage:
        # For now, echo back with a strategy label
        strategy = f"[Strategy Generated by {self.name}]: Analyze the core objective and route accordingly."

        return AINXMessage(
            role="strategist",
            sender=self.name,
            content=f"{message.content}\n\n---\n{strategy}"
        )

